//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class InOut
    {
        public int MID { get; set; }
        public bool IsIn { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ID { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
