//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWarehouse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WareHouseEntities : DbContext
    {
        public WareHouseEntities()
            : base("name=WareHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InOut> InOuts { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<VIn> VIns { get; set; }
        public virtual DbSet<VOut> VOuts { get; set; }
    }
}
