//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWarehouse
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class VOut
    {
        [DisplayName("配件名称")]
        public string Name { get; set; }
        [DisplayName("价格")]
        public Nullable<decimal> Price { get; set; }
        [DisplayName("数量")]
        public int Quantity { get; set; }
        [DisplayName("时间")]
        public Nullable<System.DateTime> Date { get; set; }
    }
}
