//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSTreeGrid.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewShop
    {
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public string ShopLei { get; set; }
        public double ShopMoney { get; set; }
        public double ShopPreMoney { get; set; }
        public bool IsSpecial { get; set; }
    }
}
