//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TestConsole.ServiceReference2.HelloWorldResponse HelloWorld(TestConsole.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TestConsole.ServiceReference2.HelloWorldResponse> HelloWorldAsync(TestConsole.ServiceReference2.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckStudent", ReplyAction="*")]
        TestConsole.ServiceReference2.CheckStudentResponse CheckStudent(TestConsole.ServiceReference2.CheckStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<TestConsole.ServiceReference2.CheckStudentResponse> CheckStudentAsync(TestConsole.ServiceReference2.CheckStudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TestConsole.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TestConsole.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestConsole.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TestConsole.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckStudent", Namespace="http://tempuri.org/", Order=0)]
        public TestConsole.ServiceReference2.CheckStudentRequestBody Body;
        
        public CheckStudentRequest() {
        }
        
        public CheckStudentRequest(TestConsole.ServiceReference2.CheckStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public CheckStudentRequestBody() {
        }
        
        public CheckStudentRequestBody(string name, string pwd) {
            this.name = name;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestConsole.ServiceReference2.CheckStudentResponseBody Body;
        
        public CheckStudentResponse() {
        }
        
        public CheckStudentResponse(TestConsole.ServiceReference2.CheckStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckStudentResult;
        
        public CheckStudentResponseBody() {
        }
        
        public CheckStudentResponseBody(bool CheckStudentResult) {
            this.CheckStudentResult = CheckStudentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TestConsole.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TestConsole.ServiceReference2.WebService1Soap>, TestConsole.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestConsole.ServiceReference2.HelloWorldResponse TestConsole.ServiceReference2.WebService1Soap.HelloWorld(TestConsole.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TestConsole.ServiceReference2.HelloWorldRequest inValue = new TestConsole.ServiceReference2.HelloWorldRequest();
            inValue.Body = new TestConsole.ServiceReference2.HelloWorldRequestBody();
            TestConsole.ServiceReference2.HelloWorldResponse retVal = ((TestConsole.ServiceReference2.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestConsole.ServiceReference2.HelloWorldResponse> TestConsole.ServiceReference2.WebService1Soap.HelloWorldAsync(TestConsole.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestConsole.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            TestConsole.ServiceReference2.HelloWorldRequest inValue = new TestConsole.ServiceReference2.HelloWorldRequest();
            inValue.Body = new TestConsole.ServiceReference2.HelloWorldRequestBody();
            return ((TestConsole.ServiceReference2.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestConsole.ServiceReference2.CheckStudentResponse TestConsole.ServiceReference2.WebService1Soap.CheckStudent(TestConsole.ServiceReference2.CheckStudentRequest request) {
            return base.Channel.CheckStudent(request);
        }
        
        public bool CheckStudent(string name, string pwd) {
            TestConsole.ServiceReference2.CheckStudentRequest inValue = new TestConsole.ServiceReference2.CheckStudentRequest();
            inValue.Body = new TestConsole.ServiceReference2.CheckStudentRequestBody();
            inValue.Body.name = name;
            inValue.Body.pwd = pwd;
            TestConsole.ServiceReference2.CheckStudentResponse retVal = ((TestConsole.ServiceReference2.WebService1Soap)(this)).CheckStudent(inValue);
            return retVal.Body.CheckStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestConsole.ServiceReference2.CheckStudentResponse> TestConsole.ServiceReference2.WebService1Soap.CheckStudentAsync(TestConsole.ServiceReference2.CheckStudentRequest request) {
            return base.Channel.CheckStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestConsole.ServiceReference2.CheckStudentResponse> CheckStudentAsync(string name, string pwd) {
            TestConsole.ServiceReference2.CheckStudentRequest inValue = new TestConsole.ServiceReference2.CheckStudentRequest();
            inValue.Body = new TestConsole.ServiceReference2.CheckStudentRequestBody();
            inValue.Body.name = name;
            inValue.Body.pwd = pwd;
            return ((TestConsole.ServiceReference2.WebService1Soap)(this)).CheckStudentAsync(inValue);
        }
    }
}
