//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public string accountNo { get; set; }
        public string IdCard { get; set; }
        public string accountName { get; set; }
        public string accountPass { get; set; }
        public string accountType { get; set; }
    }
}
