//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public string EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> workDate { get; set; }
        public string telphone { get; set; }
        public string idCard { get; set; }
        public string photo { get; set; }
    }
}
