//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadRate
    {
        public string rationType { get; set; }
        public Nullable<double> rationValue { get; set; }
    }
}
