//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyInfo
    {
        public int Id { get; set; }
        public string accountNo { get; set; }
        public System.DateTime dealDate { get; set; }
        public string dealType { get; set; }
        public double dealMoney { get; set; }
        public double balance { get; set; }
    }
}
