//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string Id { get; set; }
        public string 姓名 { get; set; }
        public string 基本工资 { get; set; }
        public string 车补贴 { get; set; }
        public string 房补贴 { get; set; }
        public string 奖金 { get; set; }
        public string 罚款 { get; set; }
        public string 总和 { get; set; }
    }
}
