//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string Id { get; set; }
        public string 姓名 { get; set; }
        public string 基本工资 { get; set; }
        public string 车补贴 { get; set; }
        public string 房补贴 { get; set; }
        public string 奖金 { get; set; }
        public string 罚款 { get; set; }
        public string 总和 { get; set; }
    }
}
