USE [ImageDb]
GO

/****** Object:  Table [dbo].[T]    Script Date: 2016-9-18 10:44:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Image1] [image] NULL,
	[Image2] [image] NULL,
 CONSTRAINT [PK__T__3214EC07C164D4E6] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


