//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSKnowledge
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB
    {
        public string Category { get; set; }
        public string Txt { get; set; }
        public byte[] Pic { get; set; }
        public int ID { get; set; }
    }
}
